config_pyiot:
  mqtt:
    server_url: "broker.mqttdashboard.com" 
    server_port: 1883
    topic_sub:  "eyrc/RiRaNiSu/iot_to_ros"
    topic_pub:  "eyrc/RiRaNiSu/ros_to_iot"
    qos:         0

    sub_cb_ros_topic: "/ros_iot_bridge/mqtt/sub"   # ROS nodes can listed to this topic to receive data from MQTT Subscription

  google_apps:
    spread_sheet_id: AKfycbwnz1QLXoB51nHoV2-shU4we9dipWDk6AO-Hd88iu1l3jJBbXft	# Spreadsheet Id/Webapp Id

